import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import About from '@component/components/About'
import Hero from '@component/components/Hero'
import Services from '@component/components/Services'
import { Fotos } from '../components/fotos'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SoftPaws PetCare</title>
        <meta name="description" content="Generated by aaa" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero  slides={Fotos}/>
      <About />
      <Services />
    </>
  )
}
